package com.vitalcare.serenia.features.socialcompanionship.presentation.circle

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import com.vitalcare.serenia.features.socialcompanionship.domain.CircleMember
import javax.inject.Inject

@HiltViewModel
class CircleViewModel @Inject constructor() : ViewModel() {

    private val _uiState = MutableStateFlow(CircleUiState())
    val uiState: StateFlow<CircleUiState> = _uiState.asStateFlow()

    private val _events = Channel<CircleEvent>(Channel.BUFFERED)
    val events: Flow<CircleEvent> = _events.receiveAsFlow()

    // The codes will be generated by the safety network once it is available
    private val sampleCodes = listOf("4821", "7305", "1946")
    private var codeIndex = 0

    fun loadCircle() {
        // The members will come from the linked family once it is available
        val members = listOf(
            CircleMember(id = 1, name = "Lucía", relationship = "Tu hija", initials = "LM"),
            CircleMember(id = 2, name = "Martín", relationship = "Tu nieto", initials = "MR")
        )

        _uiState.update { currentState ->
            currentState.copy(
                invitationCode = sampleCodes[codeIndex],
                members = members
            )
        }
    }

    fun copyCode() {
        viewModelScope.launch {
            _events.send(CircleEvent.CodeCopied)
        }
    }

    fun renewCode() {
        codeIndex = (codeIndex + 1) % sampleCodes.size

        _uiState.update { currentState ->
            currentState.copy(invitationCode = sampleCodes[codeIndex])
        }
        viewModelScope.launch {
            _events.send(CircleEvent.CodeRenewed)
        }
    }

    fun askToRemove(memberId: Int) {
        // Only one member can wait for confirmation at a time
        _uiState.update { currentState ->
            currentState.copy(memberPendingRemovalId = memberId)
        }
    }

    fun cancelRemoval() {
        _uiState.update { currentState ->
            currentState.copy(memberPendingRemovalId = null)
        }
    }

    fun confirmRemoval() {
        val currentState = _uiState.value
        val member = currentState.members.find { it.id == currentState.memberPendingRemovalId }
            ?: return

        _uiState.update { state ->
            state.copy(
                members = state.members.filterNot { it.id == member.id },
                memberPendingRemovalId = null
            )
        }
        viewModelScope.launch {
            _events.send(CircleEvent.MemberRemoved(member.name))
        }
    }

    init {
        loadCircle()
    }
}
